-- MySQL Script generated by MySQL Workbench
-- Sex 25 Out 2019 08:10:04 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MinhaPousada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MinhaPousada
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `MinhaPousada` DEFAULT CHARACTER SET utf8 ;
USE `MinhaPousada` ;

-- -----------------------------------------------------
-- Table `MinhaPousada`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Usuarios` (
  `usuaCpf` VARCHAR(11) NOT NULL,
  `usuaNome` VARCHAR(45) NOT NULL,
  `usuaEmail` VARCHAR(55) NOT NULL,
  `usuaSenha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuaCpf`))
ENGINE = InnoDB;

INSERT INTO `Usuarios` (`usuaCpf`, `usuaNome`, `usuaEmail`, `usuaSenha`) VALUES
('00752772040', 'Aristeu Alterado', 'aristeu@@@', 'senha'),
('35469593029', 'Arthur', 'asdfasdfas', 'senha2');



-- -----------------------------------------------------
-- Table `MinhaPousada`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Clientes` (
  `clieUsuaCpf` VARCHAR(11) NOT NULL,
  `clieFone1` VARCHAR(15) NULL,
  `clieFone2` VARCHAR(15) NULL,
  `clieEndereco` VARCHAR(100) NOT NULL,
  `clieComplementoEndereco` VARCHAR(45) NULL,
  `clieCidade` VARCHAR(45) NOT NULL,
  `clieUf` VARCHAR(2) NULL,
  INDEX `fk_Clientes_Usuarios1_idx` (`clieUsuaCpf` ASC),
  PRIMARY KEY (`clieUsuaCpf`),
  CONSTRAINT `fk_Clientes_Usuarios1`
    FOREIGN KEY (`clieUsuaCpf`)
    REFERENCES `MinhaPousada`.`Usuarios` (`usuaCpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `Clientes` (`clieUsuaCpf`, `clieFone1`, `clieFone2`, `clieEndereco`, `clieComplementoEndereco`, `clieCidade`, `clieUf`) VALUES
('00752772040', '32423423423', '4234234234', '234324234234', '234234234', 'inhumas', 'GO'),
('35469593029', '32423423', '324234234234', '234234234234', '2342342342342', 'sdkflgjwsaf', 'MG');

-- -----------------------------------------------------
-- Table `MinhaPousada`.`Quartos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Quartos` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Quartos` (
  `quarNumero` INT NOT NULL,
  `quarNome` VARCHAR(45) NOT NULL,
  `quarDescricao` VARCHAR(400) NOT NULL,
  `quarQtdeHospedes` INT NOT NULL,
  PRIMARY KEY (`quarNumero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinhaPousada`.`Fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Fotos` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Fotos` (
  `fotoId` INT NOT NULL AUTO_INCREMENT,
  `fotoTitulo` VARCHAR(45) NOT NULL,
  `fotoQuarNumero` INT NOT NULL,
  `fotoImagem` BLOB NOT NULL,
  `fotoExtensao` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`fotoId`),
  INDEX `fk_Fotos_Quartos_idx` (`fotoQuarNumero` ASC),
  CONSTRAINT `fk_Fotos_Quartos`
    FOREIGN KEY (`fotoQuarNumero`)
    REFERENCES `MinhaPousada`.`Quartos` (`quarNumero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinhaPousada`.`Reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Reservas` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Reservas` (
  `reseClieCpf` VARCHAR(11) NOT NULL,
  `reseQuarNumero` INT NOT NULL,
  `reseDataInicial` DATE NOT NULL,
  `reseDataFinal` DATE NOT NULL,
  `reseData` DATE NOT NULL,
  PRIMARY KEY (`reseClieCpf`, `reseQuarNumero`, `reseDataInicial`),
  INDEX `fk_Clientes_has_Quartos_Quartos1_idx` (`reseQuarNumero` ASC),
  UNIQUE INDEX `uq_reserva` (`reseClieCpf` ASC, `reseQuarNumero` ASC, `reseDataInicial` ASC),
  CONSTRAINT `fk_Clientes_has_Quartos_Quartos1`
    FOREIGN KEY (`reseQuarNumero`)
    REFERENCES `MinhaPousada`.`Quartos` (`quarNumero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_reserva`
    FOREIGN KEY (`reseClieCpf`)
    REFERENCES `MinhaPousada`.`Clientes` (`clieUsuaCpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MinhaPousada`.`Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MinhaPousada`.`Administradores` ;

CREATE TABLE IF NOT EXISTS `MinhaPousada`.`Administradores` (
  `admnUsuaCpf` VARCHAR(11) NOT NULL,
  INDEX `fk_Administradores_Usuarios1_idx` (`admnUsuaCpf` ASC),
  CONSTRAINT `fk_Administradores_Usuarios1`
    FOREIGN KEY (`admnUsuaCpf`)
    REFERENCES `MinhaPousada`.`Usuarios` (`usuaCpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `Administradores` (`admnUsuaCpf`) VALUES
('35469593029');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
